// react/src/components/collapse/item/index.tsx
import type { PropsWithClassName } from '@/types'
import { Context, type IItemProps } from '../types'
import classNames from 'classnames'
import { useContext, useMemo, type PropsWithChildren } from 'react'
import LarkIcon from '@/components/icon'
import { useDisplayNone } from '@/hooks'

function LarkCollapseItem(props: PropsWithClassName<PropsWithChildren<IItemProps>>) {
  const { disabled, name, title, className, children } = props
  const contextValue = useContext(Context)

  const isActive = useMemo(() => {
    if (!contextValue) {
      return false
    }
    return contextValue.activeNames.includes(name)
  }, [contextValue, name])

  const handleClick = () => {
    if (disabled) {
      return
    }
    contextValue?.handleClick(name)
  }

  return (
    <div
      className={classNames(className, 'lark-collapse-item', {
        'is-disabled': disabled,
      })}
    >
      <div
        className={classNames('lark-collapse-item__title', {
          'is-active': isActive,
        })}
        onClick={handleClick}
      >
        <span>{title}</span>
        <LarkIcon icon="angle-right" />
      </div>

      {useDisplayNone(isActive, <div className="lark-collapse-item__content">{children}</div>)}
    </div>
  )
}

export default LarkCollapseItem

// vue/src/components/collapse/item/index.vue
<script setup lang="ts">
import { COLLAPSE_CONTEXT_KEY, type IItemProps } from '../types'
import type { IContext } from '../types'
import { computed, inject, toRefs } from 'vue'
import LarkIcon from '@/components/icon/index.vue'

defineOptions({
  name: 'LarkCollapseItem',
})

const props = defineProps<IItemProps>()
const { disabled, name } = toRefs(props)
const context = inject<IContext>(COLLAPSE_CONTEXT_KEY)

const isActive = computed(() => {
  return context?.activeNames.value.includes(name.value)
})

const handleClick = () => {
  if (disabled.value) {
    return
  }
  context?.handleClick(name.value)
}
</script>

<template>
  <div class="lark-collapse-item" :class="{ 'is-disabled': disabled }">
    <div class="lark-collapse-item__title" :class="{ 'is-active': isActive }" @click="handleClick">
      <span>{{ title }}</span>
      <LarkIcon icon="angle-right" />
    </div>

    <div class="lark-collapse-item__content" v-show="isActive">
      <slot></slot>
    </div>
  </div>
</template>
