// react/src/components/form/item/index.tsx
import {
  useContext,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  type PropsWithChildren,
} from 'react'
import {
  FormContext,
  FormItemContext,
  type IFormItemContext,
  type IFormItemRule,
  type IItemExpose,
  type IItemProps,
  type IValidateStatus,
} from '../types'
import AsyncValidator, { type RuleItem, type ValidateError } from 'async-validator'
import classNames from 'classnames'

function LarkFormItem(props: PropsWithChildren<IItemProps>) {
  const { showErrorMsg = true, field, children, label } = props

  const [validateStatus, setValidateStatus] = useState<IValidateStatus>({
    state: 'idle',
    errorMsg: '',
  })

  const ref = useRef<(HTMLDivElement & IItemExpose) | null>(null)

  const formContext = useContext(FormContext)

  const itemValue = useMemo(() => {
    const { formData } = formContext
    if (field in formData) {
      return formData[field]
    }
    return null
  }, [formContext])

  const itemRules = useMemo(() => {
    const { rules } = formContext
    if (field in rules) {
      return rules[field]
    }
    return []
  }, [formContext])

  const isRequired = useMemo<boolean>(() => {
    return itemRules?.some((rule) => rule.required) ?? false
  }, [itemRules])

  const getTriggeredRules = (trigger?: IFormItemRule['trigger']): RuleItem[] => {
    return (
      (itemRules?.filter((rule) => {
        if (!trigger || !rule.trigger) {
          return true
        }
        return rule.trigger === trigger
      }) as RuleItem[]) ?? []
    )
  }

  const validate: IItemExpose['validate'] = async () => {
    const triggeredRules = getTriggeredRules(formContext?.trigger)
    if (triggeredRules.length === 0) {
      return
    }
    const validator = new AsyncValidator({
      [field]: triggeredRules,
    })
    setValidateStatus((prev) => ({ ...prev, state: 'validating' }))
    try {
      await validator.validate({ [field]: itemValue })
      setValidateStatus((prev) => ({ ...prev, state: 'idle' }))
      return
    } catch (err) {
      const { errors } = err as { errors: ValidateError[] }
      setValidateStatus({
        state: 'error',
        errorMsg: errors.map((e) => e.message).join('\n'),
      })
      throw errors.map((e) => e.message)
    }
  }

  const clearValidate: IItemExpose['clearValidate'] = () => {
    setValidateStatus({ state: 'idle', errorMsg: '' })
  }

  let initialVal: unknown = undefined

  const resetField: IItemExpose['resetField'] = () => {
    clearValidate()
    if (!formContext) {
      return
    }
    const { formData } = formContext
    if (field in formData) {
      console.log('resetField', { [field]: initialVal })
      formContext.setFormData((prev) => ({ ...prev, [field]: initialVal }))
    }
  }

  const formItemContext: IFormItemContext = {
    el: ref.current,
    field,
    validate,
    clearValidate,
    resetField,
  }

  useEffect(() => {
    formContext?.addField(formItemContext)
    initialVal = itemValue

    return () => {
      formContext?.removeField(formItemContext)
    }
  }, [])

  useImperativeHandle<IItemExpose, IItemExpose>(ref, () => {
    return {
      validateStatus,
      validate,
      clearValidate,
      resetField,
    }
  }, [validateStatus])

  const computedClass = useMemo(
    () => ({
      'is-error': validateStatus.state === 'error',
      'is-required': isRequired,
    }),
    [validateStatus, isRequired],
  )

  return (
    <FormContext.Consumer>
      {(formContext) => (
        <div className={classNames('lark-form-item', computedClass)} ref={ref}>
          <FormItemContext.Provider value={formItemContext}>
            <div className="lark-form-item__label">{label}</div>
            <div className="lark-form-item__content">
              {children}
              {showErrorMsg && validateStatus.state === 'error' && (
                <div className="lark-form-item__error-msg">{validateStatus.errorMsg}</div>
              )}
            </div>
          </FormItemContext.Provider>
        </div>
      )}
    </FormContext.Consumer>
  )
}

export default LarkFormItem

// vue/src/components/form/item/index.vue
<script setup lang="ts">
import {
  computed,
  inject,
  onMounted,
  onUnmounted,
  provide,
  reactive,
  toRef,
  useTemplateRef,
} from 'vue'
import type { IItemExpose, IItemProps, IItemSlots, IValidateStatus } from '../types'
import {
  FORM_CONTEXT_KEY,
  FORM_ITEM_CONTEXT_KEY,
  type IFormContext,
  type IFormItemContext,
  type IFormItemRule,
} from '../types'
import AsyncValidator, { type RuleItem, type ValidateError } from 'async-validator'

defineOptions({
  name: 'LarkFormItem',
})

const props = withDefaults(defineProps<IItemProps>(), {
  showErrorMsg: true,
})

const field = toRef(props, 'field')

const formContext = inject<IFormContext>(FORM_CONTEXT_KEY)

const validateStatus = reactive<IValidateStatus>({
  state: 'idle',
  errorMsg: '',
})

const ref = useTemplateRef('lark-form-item')

const itemValue = computed(() => {
  if (!formContext) {
    return null
  }
  const { modelValue } = formContext
  if (field.value in modelValue) {
    return modelValue[field.value]
  }
  return null
})

const itemRules = computed(() => {
  if (!formContext) {
    return []
  }
  const { rules } = formContext
  if (field.value in rules) {
    return rules[field.value]
  }
  return []
})

const isRequired = computed<boolean>(() => {
  return itemRules.value?.some((rule) => rule.required) ?? false
})

const getTriggeredRules = (trigger?: IFormItemRule['trigger']): RuleItem[] => {
  return (
    (itemRules.value?.filter((rule) => {
      if (!trigger || !rule.trigger) {
        return true
      }
      return rule.trigger === trigger
    }) as RuleItem[]) ?? []
  )
}

const validate: IItemExpose['validate'] = async () => {
  const triggeredRules = getTriggeredRules(formContext?.trigger)
  if (triggeredRules.length === 0) {
    return
  }
  const validator = new AsyncValidator({
    [field.value]: triggeredRules,
  })
  validateStatus.state = 'validating'
  try {
    await validator.validate({ [field.value]: itemValue.value })
    validateStatus.state = 'idle'
    return
  } catch (err) {
    const { errors } = err as { errors: ValidateError[] }
    validateStatus.state = 'error'
    validateStatus.errorMsg = errors.map((e) => e.message).join('\n')
    throw errors.map((e) => e.message)
  }
}

const clearValidate: IItemExpose['clearValidate'] = () => {
  validateStatus.state = 'idle'
  validateStatus.errorMsg = ''
}

let initialVal: unknown = undefined

const resetField: IItemExpose['resetField'] = () => {
  clearValidate()
  if (!formContext) {
    return
  }
  const { modelValue } = formContext
  if (field.value in modelValue) {
    formContext.setModelValue(field.value, initialVal)
  }
}

const formItemContext: IFormItemContext = {
  el: ref.value,
  field: field.value,
  validate,
  clearValidate,
  resetField,
}

provide(FORM_ITEM_CONTEXT_KEY, formItemContext)

onMounted(() => {
  formContext?.addField(formItemContext)
  initialVal = itemValue.value
})

onUnmounted(() => {
  formContext?.removeField(formItemContext)
})

defineExpose<IItemExpose>({
  validateStatus,
  validate,
  clearValidate,
  resetField,
})

defineSlots<IItemSlots>()
</script>

<template>
  <div
    class="lark-form-item"
    ref="lark-form-item"
    :class="{
      'is-error': validateStatus.state === 'error',
      'is-required': isRequired,
    }"
  >
    <div class="lark-form-item__label">
      <slot name="label" :label="label">{{ label }}</slot>
    </div>
    <div class="lark-form-item__content">
      <slot :validate="validate"></slot>
      <div
        class="lark-form-item__error-msg"
        v-if="showErrorMsg && validateStatus.state === 'error'"
      >
        {{ validateStatus.errorMsg }}
      </div>
    </div>
  </div>
</template>
