// react/src/components/alert/index.tsx
import { useMemo, useRef, useState } from 'react'
import type { IProps } from './types'
import { CSSTransition } from 'react-transition-group'
import classNames from 'classnames'
import LarkIcon from '@/components/icon'
import type { PropsWithClassName } from '@/types'
import type { MouseEvent } from 'react'

function LarkAlert(props: PropsWithClassName<IProps>) {
  const {
    closable = true,
    effect = 'light',
    type,
    center,
    showIcon,
    title,
    description,
    closeText,
    className,
    onClose,
  } = props

  const computedClass = useMemo(
    () => [
      `lark-alert--${type}`,
      `lark-alert--${effect}`,
      {
        'is-center': center,
      },
    ],
    [type, effect, center],
  )

  const [alive, setAlive] = useState(true)

  const alertIcon = useMemo(() => {
    switch (type) {
      case 'error': {
        return 'circle-xmark'
      }
      case 'info': {
        return 'circle-info'
      }
      case 'success': {
        return 'circle-check'
      }
      case 'warning': {
        return 'circle-exclamation'
      }
      default: {
        return 'circle-info'
      }
    }
  }, [type])

  const handleClose = (e: MouseEvent) => {
    setAlive(false)
    onClose?.(e)
  }

  const nodeRef = useRef<HTMLDivElement | null>(null)

  return (
    <CSSTransition nodeRef={nodeRef} classNames="fade" in={alive} unmountOnExit timeout={200}>
      <div className={classNames(className, 'lark-alert', computedClass)} ref={nodeRef}>
        <div className="lark-alert__content">
          {showIcon && (
            <span className="lark-alert__icon">
              <LarkIcon
                icon={alertIcon}
                onClick={() => {
                  setAlive(false)
                }}
              />
            </span>
          )}

          <div className="lark-alert__message">
            <p className="lark-alert__title">{title}</p>

            {description && <p className="lark-alert__description">{description}</p>}
          </div>
        </div>

        {closable &&
          (closeText ? (
            <div onClick={handleClose} className="close-btn">
              {closeText}
            </div>
          ) : (
            <LarkIcon icon="xmark" onClick={handleClose} className="close-btn" />
          ))}
      </div>
    </CSSTransition>
  )
}

export default LarkAlert

// vue/src/components/alert/index.vue
<script setup lang="ts">
import { computed, ref, toRefs } from 'vue'
import type { IEmits, IProps } from './types'
import LarkIcon from '@/components/icon/index.vue'

defineOptions({
  name: 'LarkAlert',
})

const props = withDefaults(defineProps<IProps>(), {
  closable: true,
  effect: 'light',
})

const { type, center, effect } = toRefs(props)

const emits = defineEmits<IEmits>()

const computedClass = computed(() => {
  return [`lark-alert--${type.value}`, `lark-alert--${effect.value}`, { 'is-center': center }]
})

const alive = ref(true)

const handleClose = (e: MouseEvent) => {
  alive.value = false
  emits('close', e)
}

const alertIcon = computed(() => {
  switch (type.value) {
    case 'error': {
      return 'circle-xmark'
    }
    case 'info': {
      return 'circle-info'
    }
    case 'success': {
      return 'circle-check'
    }
    case 'warning': {
      return 'circle-exclamation'
    }
    default: {
      return 'circle-info'
    }
  }
})
</script>

<template>
  <!-- name 是 CSS 类选择器名的前缀, 默认值是 v- -->
  <!-- v-[enter | leave]-[from | active | to] -->
  <Transition name="fade">
    <div class="lark-alert" :class="computedClass" v-if="alive">
      <div class="lark-alert__content">
        <span v-if="showIcon" class="lark-alert__icon">
          <!-- .stop: event.stopPropagation() -->
          <LarkIcon :icon="alertIcon" @click.stop="alive = false" />
        </span>

        <div class="lark-alert__message">
          <p class="lark-alert__title">
            {{ title }}
          </p>

          <p v-if="description" class="lark-alert__description">
            {{ description }}
          </p>
        </div>
      </div>

      <!-- <template /> 类似 React Fragment </> -->
      <template v-if="closable">
        <div v-if="closeText" @click="handleClose" class="close-btn">{{ closeText }}</div>
        <LarkIcon v-else icon="xmark" @click="handleClose" class="close-btn" />
      </template>
    </div>
  </Transition>
</template>
